on:
  issue_comment:
    types: [created, edited]

jobs:
  parse-comment:
    runs-on: ubuntu-latest
    name: Parse Comment
    steps:
      - name: Issue Refs Parser Action
        uses: FujiHaruka/issue-refs-parser-action@v1.1
        id: action
        with:
          body: ${{ github.event.comment.body }}
          self_slug: hugo-toha/toha
      - name: Get The Outputs
        run: |
          echo "refs: ${{ steps.action.outputs.refs }}"
          echo "external_refs: ${{ steps.action.outputs.external_refs }}"
